#!/usr/bin/env php
<?php
use Symfony\Component\Console\Application;

define( 'DPOH_ROOT', __DIR__ );

require __DIR__.'/vendor/autoload.php';

require_once 'includes/arrays.php';
require_once 'includes/autoloader.php';
require_once 'includes/bootstrap.php';
require_once 'includes/database.php';
require_once 'includes/exceptions.php';
require_once 'includes/files.php';
require_once 'includes/models.php';
require_once 'includes/security.php';
require_once 'includes/templates.php';

require_once 'vendor/paragonie/random_compat/lib/random.php';
require_once 'vendor/paragonie/random_compat/lib/random.php';

spl_autoload_register( 'vortex_autoloader' );

$application = new Application();
$data = [ 'application' => $application ];
fire_hook( 'provide_console_commands', $data );
$application->run();
