#!/usr/bin/env php
<?php
use Symfony\Component\Console\Application;
use Vortex\App as VortexApp;

define( 'DPOH_ROOT', __DIR__ );

require __DIR__.'/vendor/autoload.php';

require_once 'includes/arrays.php';
require_once 'includes/bootstrap.php';
require_once 'includes/database.php';
require_once 'includes/exceptions.php';
require_once 'includes/files.php';
require_once 'includes/html.php';
require_once 'includes/security.php';
require_once 'includes/templates.php';

require_once 'vendor/paragonie/random_compat/lib/random.php';

$vortex_app = new VortexApp(DPOH_ROOT . '/modules_enabled', DPOH_ROOT . '/settings-global.ini');
VortexApp::setInstance($vortex_app);
date_default_timezone_set( $vortex_app->settings->get( 'timezone' ) );

$whoops = new Whoops\Run;
$whoops->pushHandler( new Whoops\Handler\PlainTextHandler );
$whoops->register();

$application = new Application();
$data = [ 'application' => $application ];
$vortex_app->fireHook( 'provide_console_commands', $data );
$application->run();
