#!/bin/bash

cd $(dirname $(realpath $0) )

echo "Building Vortex base image..."
docker image build -q -t vortex-base ../docker/web > /dev/null

echo "Building test image based on Vortex base image..."
IMG_ID=$(docker image build image/ -q)
rm -fr image/vortex

echo "Creating container for tests..."
CONTAINER_ID=$(docker container create $IMG_ID)

echo "Copying Vortex source to test environment..."
docker cp ../ $CONTAINER_ID:/var/www/html/vortex/

echo "Starting container for tests..."
docker container start $CONTAINER_ID -ia &
PID=$!

function cleanup() {
    docker container rm -f $CONTAINER_ID > /dev/null # Force removal on script exit in case of, e.g., infinite loop within tests
}

trap cleanup EXIT
wait $PID
